### ISSUE TITLE
more information about the freqSUBTLEX column

### ISSUE THREAD

**Issue by bnicenboim** [jaytimm/lexvarsdatr#1]
Hi, nice work!

Question:
Which one of the measures from https://www.ugent.be/pp/experimentele-psychologie/en/research/documents/subtlexus freqSUBTLEX corresponds?

**Comment by jaytimm** [comment]
Hi -- Sorry for the slow response.

Values originally from Brysbaert & New, 2009.  Frequency per 1 million words.
